<div class="lw-card lw-qr-preview lw-qr-preview-horizontal">
	<h2>Your review + loyalty QR code</h2>
	<div class="lw-qr-frame <?php echo $google['review_url'] ? '' : 'is-empty'; ?>">
		<img id="lw-qr-image" src="<?php echo esc_url( $google['qr_image_url'] ); ?>" data-flow-url="<?php echo esc_attr( $google['flow_url'] ?? '' ); ?>" alt="Google review and loyalty card QR code preview" <?php echo $google['review_url'] ? '' : 'hidden'; ?>>
		<p id="lw-qr-empty" <?php echo $google['review_url'] ? 'hidden' : ''; ?>>Enter a Place ID to generate your review QR code.</p>
	</div>
	<div id="lw-qr-actions" class="lw-qr-actions" <?php echo $google['review_url'] ? '' : 'hidden'; ?>>
		<a id="lw-qr-open" class="button lw-qr-action-button" href="<?php echo esc_url( $google['flow_url'] ?? $google['review_url'] ); ?>" target="_blank" rel="noopener noreferrer"><span class="dashicons dashicons-external"></span>Open link</a>
		<button id="lw-qr-copy" class="button lw-qr-action-button" type="button" data-url="<?php echo esc_attr( $google['flow_url'] ?? $google['review_url'] ); ?>"><span class="dashicons dashicons-clipboard"></span><span class="lw-copy-label">Copy link</span></button>
		<button type="button" class="button lw-qr-action-button lw-open-redemption"><span class="dashicons dashicons-cart"></span>Canjear</button>
		<small id="lw-qr-copy-status" role="status" aria-live="polite"></small>
	</div>
	<div class="lw-latest-review"><hr class="lw-settings-divider"><h2>Latest Google review <?php if ( $google['sandbox_mode'] ) : ?><span class="lw-sandbox-badge">Sandbox</span><?php endif; ?></h2><div id="lw-latest-stars" class="lw-review-stars" aria-label="<?php echo $google['sandbox_mode'] ? '5 out of 5 stars' : 'No rating available'; ?>"><?php echo $google['sandbox_mode'] ? '★★★★★' : '☆☆☆☆☆'; ?></div><blockquote id="lw-latest-text" class="lw-review-text"><?php echo $google['sandbox_mode'] ? 'Excellent service. I would definitely visit again!' : 'Your latest customer review will appear here after Google Business Profile is connected.'; ?></blockquote><div class="lw-review-meta"><span class="dashicons dashicons-admin-users"></span><span><strong id="lw-latest-name"><?php echo $google['sandbox_mode'] ? 'Test Customer' : 'Reviewer name'; ?></strong><small id="lw-latest-date"><?php echo $google['sandbox_mode'] ? '5 stars · Sandbox review' : 'Date and rating pending'; ?></small></span></div><div class="lw-review-check"><label for="lw-review-search">Check review by customer name</label><div><input id="lw-review-search" type="search" placeholder="Customer name"><button id="lw-review-search-button" type="button" class="button">Check review</button></div><p id="lw-review-search-result" aria-live="polite"></p><form id="lw-add-customer-form" class="lw-add-customer" method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" hidden><input type="hidden" name="action" value="loyalty_wallet_add_customer"><?php wp_nonce_field( 'loyalty_wallet_add_customer' ); ?><input id="lw-customer-name" type="hidden" name="customer_name"><input type="hidden" name="customer_review" value="Excellent service. I would definitely visit again!"><input type="hidden" name="customer_rating" value="5"><input type="hidden" name="customer_review_date" value="<?php echo esc_attr( current_time( 'Y-m-d' ) ); ?>"><label for="lw-customer-email">Customer email</label><input id="lw-customer-email" name="customer_email" type="email" placeholder="customer@example.com" required><label for="lw-customer-phone">Customer phone</label><input id="lw-customer-phone" name="customer_phone" type="tel" placeholder="+1 555 123 4567" required><button type="submit" class="button button-primary">Add client</button></form></div></div>
</div>
